### ISSUE TITLE
vlt bug beim kicken

### ISSUE THREAD

**Issue by Taracraft** [Taracraft/Fachinformatiker-Discord#15]
Benutzer gefunden Paco_Jerte
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<status_task() done, defined at /home/git/Fachinformatiker-Discord/Bot/rollencheck.py:29> exception=Forbidden('403 Forbidden (error code: 50007): Cannot send messages to this user')>
Traceback (most recent call last):
  File "/home/git/Fachinformatiker-Discord/Bot/rollencheck.py", line 58, in status_task
    await getuser.send(embed=embed)
  File "/root/.local/lib/python3.9/site-packages/discord/abc.py", line 1539, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/root/.local/lib/python3.9/site-packages/discord/http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user

**Comment by Taracraft** [comment]
da man das nicht umgehen kann > closed
